"""Server-side PDF generation using reportlab (pure-Python, no native
system libraries required — a deliberate swap for WeasyPrint so Docker
builds stay simple)."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet


def _doc(buffer):
    return SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)


def render_rent_statement_pdf(lease, payments, generated_by: str, charges=None) -> bytes:
    buffer = io.BytesIO()
    styles = getSampleStyleSheet()
    elements = [
        Paragraph("RentalPro — Rent Statement", styles["Title"]),
        Paragraph(f"Tenant: {lease.tenant.user.full_name}", styles["Normal"]),
        Paragraph(f"Unit: {lease.unit.unit_code} ({lease.unit.property.name})", styles["Normal"]),
        Paragraph(f"Period: {lease.start_date} to {lease.end_date}", styles["Normal"]),
        Paragraph(f"Generated by {generated_by}", styles["Normal"]),
        Spacer(1, 0.3 * inch),
    ]

    rows = [["Date", "Type", "Description", "Amount", "Receipt #"]]
    for p in payments:
        rows.append([str(p.paid_at.date()), "Payment", p.notes or "Rent payment", f"-{p.amount:.2f}", p.receipt_number])
    for c in charges or []:
        rows.append([str(c.charged_at), c.charge_type.title(), c.description, f"{c.amount:.2f}", "-"])
    table = Table(rows, colWidths=[1.1 * inch, 1.0 * inch, 2.1 * inch, 1.0 * inch, 1.3 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(f"Rent charged to date: {lease.total_due_to_date():.2f}", styles["Normal"]))
    if charges:
        elements.append(Paragraph(f"Operational/sundry charges: {lease.total_charges:.2f}", styles["Normal"]))
    elements.append(Paragraph(f"Total paid: {lease.total_paid:.2f}", styles["Normal"]))
    elements.append(Paragraph(f"Outstanding balance: {lease.balance:.2f}", styles["Heading3"]))

    _doc(buffer).build(elements)
    return buffer.getvalue()


def render_property_report_pdf(property_obj, summary: dict) -> bytes:
    buffer = io.BytesIO()
    styles = getSampleStyleSheet()
    elements = [
        Paragraph("RentalPro — Property Performance Report", styles["Title"]),
        Paragraph(f"Property: {property_obj.name} ({property_obj.property_code})", styles["Normal"]),
        Spacer(1, 0.3 * inch),
    ]
    rows = [["Metric", "Value"]] + [[k, str(v)] for k, v in summary.items()]
    table = Table(rows, colWidths=[3 * inch, 2 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ]
        )
    )
    elements.append(table)
    _doc(buffer).build(elements)
    return buffer.getvalue()
