"""Server-side PDF generation using reportlab (pure-Python, no native
system libraries required — a deliberate swap for WeasyPrint so Docker
builds stay simple)."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet


def _doc(buffer):
    return SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)


def render_rent_statement_pdf(
    lease, payments, generated_by: str, charges=None, period_start=None, period_end=None, period_totals=None
) -> bytes:
    buffer = io.BytesIO()
    styles = getSampleStyleSheet()
    elements = [
        Paragraph("RentalPro — Rent Statement", styles["Title"]),
        Paragraph(f"Tenant: {lease.tenant.user.full_name}", styles["Normal"]),
        Paragraph(f"Unit: {lease.unit.unit_code} ({lease.unit.property.name})", styles["Normal"]),
        Paragraph(f"Lease term: {lease.start_date} to {lease.end_date}", styles["Normal"]),
    ]
    if period_start:
        elements.append(Paragraph(f"Statement period: {period_start} to {period_end}", styles["Normal"]))
    elements.append(Paragraph(f"Generated by {generated_by}", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))

    if period_totals:
        elements.append(Paragraph(f"Opening balance: {period_totals['opening_balance']:.2f}", styles["Normal"]))

    rows = [["Date", "Type", "Description", "Amount", "Receipt #"]]
    for p in payments:
        rows.append([str(p.paid_at.date()), "Payment", p.notes or "Rent payment", f"-{p.amount:.2f}", p.receipt_number])
    for c in charges or []:
        rows.append([str(c.charged_at), c.charge_type.title(), c.description, f"{c.amount:.2f}", "-"])
    table = Table(rows, colWidths=[1.1 * inch, 1.0 * inch, 2.1 * inch, 1.0 * inch, 1.3 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))

    if period_totals:
        elements.append(Paragraph(f"Rent charged this period: {period_totals['rent_in_period']:.2f}", styles["Normal"]))
        if period_totals["charges_in_period"]:
            elements.append(Paragraph(f"Operational/sundry charges this period: {period_totals['charges_in_period']:.2f}", styles["Normal"]))
        elements.append(Paragraph(f"Paid this period: {period_totals['payments_in_period']:.2f}", styles["Normal"]))
        elements.append(Paragraph(f"Closing balance: {period_totals['closing_balance']:.2f}", styles["Heading3"]))
    else:
        elements.append(Paragraph(f"Rent charged to date: {lease.total_due_to_date():.2f}", styles["Normal"]))
        if lease.current_monthly_rent != lease.monthly_rent:
            elements.append(Paragraph(f"Current monthly rent: {lease.current_monthly_rent:.2f} (original {lease.monthly_rent:.2f})", styles["Normal"]))
        if charges:
            elements.append(Paragraph(f"Operational/sundry charges: {lease.total_charges:.2f}", styles["Normal"]))
        elements.append(Paragraph(f"Total paid: {lease.total_paid:.2f}", styles["Normal"]))
        elements.append(Paragraph(f"Outstanding balance: {lease.balance:.2f}", styles["Heading3"]))

    _doc(buffer).build(elements)
    return buffer.getvalue()


def render_property_report_pdf(property_obj, summary: dict) -> bytes:
    buffer = io.BytesIO()
    styles = getSampleStyleSheet()
    elements = [
        Paragraph("RentalPro — Property Performance Report", styles["Title"]),
        Paragraph(f"Property: {property_obj.name} ({property_obj.property_code})", styles["Normal"]),
        Spacer(1, 0.3 * inch),
    ]
    rows = [["Metric", "Value"]] + [[k, str(v)] for k, v in summary.items()]
    table = Table(rows, colWidths=[3 * inch, 2 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ]
        )
    )
    elements.append(table)
    _doc(buffer).build(elements)
    return buffer.getvalue()
