"""Save each user's language

Revision ID: 862aa1e668eb
Revises: bcde74b31ea7
Create Date: 2026-09-29 20:57:06.232699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862aa1e668eb'
down_revision = 'bcde74b31ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
